name: flutter_application_1
description: View PDFs using file_selector (Web + Android)

version: 1.0.0
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  file_picker: ^10.2.0
  syncfusion_flutter_pdf: ^30.1.38
  pdfx: 2.9.2  # PDF viewer package
  path_provider: ^2.1.1  # For file handling

dev_dependencies:
  flutter_test:
    sdk: flutter